#!/usr/bin/env bash
# Train and evaluate CCE-Net (triplet) on Maryland-PolyVore.
set -e

FILE=train_cce_triplet.py
DATA_DIR="../outfits-hf"
DATA_SET="maryland-polyvore/original"
LOG_DIR="runs/maryland-polyvore-triplet"
FLAGS="--norm --feat-norm --neg-type-aware --trans-layer"
OPTS="--tau 0.10 --base-model GATConv --batch-size 128 --lr 0.1 --num-layers 2 --neg-ratio 1"

# training
python $FILE --data-dir $DATA_DIR --data-set $DATA_SET --num-neg 1 --log-dir $LOG_DIR $FLAGS $OPTS --neg-mode RandomMix "$@"

# testing with random-mixed negative outfits
python $FILE --data-dir $DATA_DIR --data-set $DATA_SET --num-neg 1 --log-dir $LOG_DIR $FLAGS $OPTS \
    --neg-mode RandomMix --test --load-trained $LOG_DIR/checkpoints/net_best.pt --log-name replace-all

# testing with negative outfits generated by replacing k items
for k in 1 2 3; do
  python $FILE --data-dir $DATA_DIR --data-set $DATA_SET --num-neg 1 --log-dir $LOG_DIR $FLAGS $OPTS \
      --neg-mode RandomReplace --num-replace $k --test --load-trained $LOG_DIR/checkpoints/net_best.pt --log-name replace-$k
done
