#!/usr/bin/env bash
# Train and evaluate CCE-Net (InfoNCE) on Maryland-PolyVore.
set -e

FILE=train_cce_infonce.py
DATA_DIR="../outfits-hf"
DATA_SET="maryland-polyvore/original"
LOG_DIR="runs/maryland-polyvore-infonce"
NUMNEG=4
TAU=0.10
FLAGS="--norm --feat-norm --neg-type-aware --trans-layer"
OPTS="--tau $TAU --base-model GATConv --batch-size 128 --lr 0.1 --num-layers 2 --neg-ratio 1 --num-neg $NUMNEG"

# training
python $FILE --data-dir $DATA_DIR --data-set $DATA_SET --log-dir $LOG_DIR $FLAGS $OPTS --neg-mode RandomMix "$@"

# testing with random-mixed negative outfits
python $FILE --data-dir $DATA_DIR --data-set $DATA_SET --log-dir $LOG_DIR $FLAGS $OPTS \
    --neg-mode RandomMix --test --load-trained $LOG_DIR/checkpoints/net_best.pt --log-name replace-all

# testing with negative outfits generated by replacing k items
python $FILE --data-dir $DATA_DIR --data-set $DATA_SET --log-dir $LOG_DIR $FLAGS $OPTS \
    --neg-mode RandomReplace --num-replace 1 --test --load-trained $LOG_DIR/checkpoints/net_best.pt --log-name replace-1
